version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: daily
    allow:
      - dependency-name: '@spinnaker/kayenta'
      - dependency-name: '@spinnaker/styleguide'
