queue_rules:
  - name: default
    conditions:
      - base=master
      - status-success=Deck CI
  - name: backport
    conditions:
      - base~=^release-
      - status-success=Deck CI

pull_request_rules:
  - name: Automatically merge on CI success and review
    conditions:
      - 'label=ready to merge'
      - 'approved-reviews-by=@oss-approvers'
    actions:
      queue:
        method: squash
        name: default
  - name: Automatically self merge on CI success
    conditions:
      - 'label=ready to merge'
      - 'label=self merge'
    actions:
      queue:
        method: squash
        name: default
  - name: Automatically rebase and merge on CI success and review
    conditions:
      - 'label=ready to rebase'
      - 'approved-reviews-by=@oss-approvers'
    actions:
      queue:
        method: rebase
        name: default
  - name: Automatically rebase and self merge on CI success
    conditions:
      - 'label=ready to rebase'
      - 'label=self merge'
    actions:
      queue:
        method: rebase
        name: default
  - name: Automatically merge release branch changes on Travis CI success and release manager review
    conditions:
      - 'label=ready to merge'
      - 'approved-reviews-by=@release-managers'
    actions:
      queue:
        method: squash
        name: backport
