language: java
jdk:
- oraclejdk8
sudo: required
dist: trusty
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install: gradle/installViaTravis.sh
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - $HOME/.gradle
  - node_modules
notifications:
  slack:
    secure: tiW8Hb82slR0ldYvtoTlF8HDTwrhzgtwFFbCH8yo/1bkHhv9xRK2rF68q+DNDk9+34dDlTs5oOGYHMc8Q27S+qJUWUaj3He0BJhDTnJPaaBSOrbeMbq795hfLdGJLu4sJeTcBQ09ci51/uVl9hrNRalB2pfa/aRGvbPraxS5+TPXZpJf2x4YkMs1unTWOqbF3D1ffhgvh5R7UoqAdx/xfrQsj9aSVTvc1OrwI36vEu+bUMTvSXJ7TrdZ7rb6wR5lgcGJ1Jhk9kwyC4qvXIT09IET2Ubq7lCUwU6IqL6tHh872eRz9pG/ZQMVomlnn1gIyLu/0xI8vgxMx7UJ69ZOpeGbdNuUnEu8x+LJ/qV+O8/oc8m2DnJ9xgJCokPkmL0lv76IHxlU7G4Py6V7p28Kk59h2hCw2NSfAnsnx8pFhdu9imw2QeG5p1ueLCThq6s6tEBAYjBS0uvye6Fv62EJJd5he867aeCfm9IuXUuT33HkM0AwUo3oJuErG3errvIQiuVNK8p5vbZLNp+amBtk2tcquUUbB8g7ui61M+YNKvzGJ1ugYUo3Sp3DyvD3DFIH+kP+w3Gw85c/maYEug1CiAbHn0B2fTWpkiOkRwOrAOwN2uKSVQHW7wmXSeJiU0ggMlwTiJ8LgN/6NckqM029NuRg8TskSeSwdnGMTTCEs00=
env:
  global:
  - secure: B3KkWCFv2I+fqAIL6NcfK6is+CrTTsrhTOxRjD1DwnqduxfGOjrS+3qVD8NfIGx7O3MsCk0CCnz1xqiOFrLERf8elhCuEuVjumSpt9VZwpsd+hKmNQeuVoFABB1hlZrHdr2rDH17KVT+TgWNTDSt9Mk3cvRAq+j2BxOHxZXDi59PiVaRGiiM4/aEBtF0/zWfusGIHRGsouGENJU1Zi6xyt0MChx3SCDL2p5qMduGWYsnnUy4BnHMPBi+pF30mjKTI+9JVrecFRuSFezh+MEE67ZiJNw/6bAsZ35sPrd/ECEiELwiEUekpNyXu9/1AxlzaKzrHDnijuZJoEvIaKV8WYwjGjhljF0QNuWGkaKQUcIs4bOKxAY2E62/ZjDbb5J8P3V7k5FD/RHdbVva0A0g7twUNR1vJIk8DFFdY4zqgCRxCyKlQKTdTjk/tV/PjxX5MAQT5J6/OgNLohA8tLRN72xvnDd9XFaKV9RJW23a4xGNUBH24wn1Od11lqR2ZU6/oejXqSojee8IgsjcCXypwW0ZS6OAOjybjxlt/n0av4MKnLFaEmUvxRP26gGJ1H8nfgNCnsLAH9UD1y1XT3VmU7g32cv8AUKyxhh/IgBG2qiqjVNaWvqK8YrepnR0Rbti5AnUiLz8QwipWW3g9DUffUWR98Ubjzs3kMzorbRB7rM=
  - secure: Sy0YuNrTfgkLKvCDWDKKKrc/C1pIRz4+iD9sIA67VrhkLhyWr/+tXd5Rn49PfyY0DrbyFygQ5rrtuCQOCmKluZwkvroqTJ9n1Nu2RcoapsFoHMW5hiUaBUHVjiL1CbbOdE05uvKGxn27y/HUMdfX9w9sGQ5wlT4yRjMtt/ajtWJwy696UJwJnZRONJerJb+w4tWwafIqKdiHLpp/1P8ziilVD3lwgSLmCY8ljmvmz+2GPY/NkC4Mkk7BUgSPcWu0uKXJxGYkSnsg9jCeopzmHRT8fzEGzBYw52rf92XRMr9ghbVVGeyUXEpTW8JOQTnKmnQM0oq2/yh46pWMOdShyXp+Ys794Oo1UiLhJQUkJXc60S7ByvjA1FZH2d2m07Z9la+RzUBzM0QIJ/2Q4ZS+5YUH3hXpiAUg129/EB4+M7GzsjIthkdLpkwRMhAPJns4E2yarf3l0frN7vecC9qhB7ShdBcBAwg3rc5Mx6lAtoOis5iqMENV4HnOPVxveitZLeiMcAjU664P7D/xCx7AOxiHbiifRbAqXaYVBYjQae0pmnPHulkFqw6NPZSUdZ0PaqmAxM8DRqHsCzTgRjrBt4bgcOWt0S5skJ+Thul6dtl96dwURXQlxBEsuz6dzZ3voZGPZTqzhyQVT0yWJreyQ3oKDEn3Ip/0AwubzjnslHk=
