language: java
jdk:
- oraclejdk8
sudo: required
dist: trusty
before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
install: gradle/installViaTravis.sh
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - $HOME/.gradle
  - node_modules
env:
  global:
  - secure: c5RGrL+JcaGsI18MOMLW6kZoQRteiFrbfOoDY5JjJb7ZaACynZu1DdZ83p19nNhdzpSKBqFv/iKx7QN9vqQDXlh0M2fefWYVuh9QHhmQyyqgcc9X7pYZ2OrsLjUg2J0GZcSYaqaX/TjWuJL1lpQbdiiKqhgi915eWHLghvIgEy05UyvZVLRTVClDSeMGEKbnJ480B6crG4ads8pT3dGzVd4+WmtoAJWJpeSxMD4UEmxQ509QV9h4jKiTjPb2LZ4e1W+HLrtNm7x/g2id5IiP70GrL2MGw/V1ptlybkUOumtfZoZWOOMmTCuktG5xLM9ldp64TXhZJ/e1jTr3U4m9k4HZJRmdpJONSY8rduZiqBfoLnGWW8/FQssrbrsNhpUGEPuknRZPOVcQiSQnVHPe0+zJrCHS6OhMhkfozw2o/guE4uLtnAkLtsaCb0ZK8f+dSoQwhG4erdwOala7UqdSgtqMyU5D0Lwc2FGGb1XbiLFuLMTWn5BEs6hX+i5mAv/osxuRW3RIJpU5DOhbKq9Bv95EIMhgGvUotNBVubsdOgUK/7D43bTEpUHshCAUsnBPhWt85eido4sAth2FEcbxeIvLFAq117rR9ZbhpyZ+wVR8N8EuEC/FPGQNzprYxE9qOOIG++d4SvP1YYDlg3z88mz6C8+gYZYF7upro+7MhtA=
  - secure: SzrFpCphjsASo4kPeB73dR7/4ui1b0F/qb51nVsvAGZPdyuGufWzH/KwQSDznhLq/PsKzm9OHaNZOZ/Acn0lMNVfadWjtMrlo9y9DoC0hA1DcphOliWqjTOtMCMRwJnfXk+X46GpMzC8z+8RFMvgrUlXfhLQSV17FgAMP7JpmUUMmwq/1+XBXi0ZxpWnq3YY9N3VXgSeKSsfWSZ3HjF6BqrqzN72qv1xiO/uSlorn3TfRcszANcIJeWZAW1etDnFtYs8K2PsJADGRphfvJb2NByXLqmK2m2bVbm8/NPLoRJoMu24q2A1agFwIRtNeLw/NgrO1Xsw7cZISIKMVTBGnH+saYL8vOxb4norBnfq9eh/ZNcFGWdcv1GmfjaLuWV6HtxQYnfZnSgQLYJAC7Bw1K0mxWKEyQXowDaIc27ZvopSaQvlx9dK9jcBvWPPgXf7VrBBQSmuyu1ryuCQCmfBCYaXYlxNJ3x2N4+znLkDCJfYr6qSwk77PVDpfGXIZqz5FG1HxKTRL+3usa/iWYHKssw4POWwF0V5dpq5KtU3Jyjlnch1QGmgfgvA/S82IkNvb94sP6wznGPmZStJV7/kZthFD2eqq/yNg3B+TkEfoqQ/v2c+sDmnZMoSiQu0eCfksSVd6wcSp4w4mu8GoDapmT3dwyhuibxog0kATFwhwDw=
notifications:
  slack:
    secure: tiW8Hb82slR0ldYvtoTlF8HDTwrhzgtwFFbCH8yo/1bkHhv9xRK2rF68q+DNDk9+34dDlTs5oOGYHMc8Q27S+qJUWUaj3He0BJhDTnJPaaBSOrbeMbq795hfLdGJLu4sJeTcBQ09ci51/uVl9hrNRalB2pfa/aRGvbPraxS5+TPXZpJf2x4YkMs1unTWOqbF3D1ffhgvh5R7UoqAdx/xfrQsj9aSVTvc1OrwI36vEu+bUMTvSXJ7TrdZ7rb6wR5lgcGJ1Jhk9kwyC4qvXIT09IET2Ubq7lCUwU6IqL6tHh872eRz9pG/ZQMVomlnn1gIyLu/0xI8vgxMx7UJ69ZOpeGbdNuUnEu8x+LJ/qV+O8/oc8m2DnJ9xgJCokPkmL0lv76IHxlU7G4Py6V7p28Kk59h2hCw2NSfAnsnx8pFhdu9imw2QeG5p1ueLCThq6s6tEBAYjBS0uvye6Fv62EJJd5he867aeCfm9IuXUuT33HkM0AwUo3oJuErG3errvIQiuVNK8p5vbZLNp+amBtk2tcquUUbB8g7ui61M+YNKvzGJ1ugYUo3Sp3DyvD3DFIH+kP+w3Gw85c/maYEug1CiAbHn0B2fTWpkiOkRwOrAOwN2uKSVQHW7wmXSeJiU0ggMlwTiJ8LgN/6NckqM029NuRg8TskSeSwdnGMTTCEs00=
