<VirtualHost {%DECK_HOST%}:{%DECK_PORT%}>
  SSLEngine on
  SSLProxyEngine on
  SSLProxyVerify none
  SSLProxyCheckPeerCN off
  SSLProxyCheckPeerName off
  SSLProxyCheckPeerExpire off
  SSLCertificateFile "{%DECK_CERT_PATH%}"
  SSLCertificateKeyFile "{%DECK_KEY_PATH%}"
  
  DocumentRoot /opt/deck/html

  ProxyPass "/gate" "{%API_HOST%}" retry=0
  ProxyPassReverse "/gate" "{%API_HOST%}"

  <Directory "/opt/deck/html/">
    Require all granted
  </Directory>
</VirtualHost>
