name: Deck CI

on:
  pull_request:
    paths:
      - 'app/scripts/modules/amazon/package.json'
      - 'app/scripts/modules/appengine/package.json'
      - 'app/scripts/modules/azure/package.json'
      - 'app/scripts/modules/cloudfoundry/package.json'
      - 'app/scripts/modules/core/package.json'
      - 'app/scripts/modules/docker/package.json'
      - 'app/scripts/modules/ecs/package.json'
      - 'app/scripts/modules/google/package.json'
      - 'app/scripts/modules/huaweicloud/package.json'
      - 'app/scripts/modules/kubernetes/package.json'
      - 'app/scripts/modules/oracle/package.json'
      - 'app/scripts/modules/titus/package.json'

env:
  NODE_VERSION: 10.15.1

jobs:
  test:
    name: Approve package bumps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Approve package bump
        # pin to v2.0.0 tag by commit hash
        uses: hmarr/auto-approve-action@7782c7e
        with:
          github-token: '${{ secrets.SPINNAKERBOT_TOKEN }}'
      - name: ready to merge label
        uses: actions/github@v1.0.0
        with:
          args: label 'ready to merge'
        env:
          GITHUB_TOKEN: ${{ secrets.SPINNAKERBOT_TOKEN }}
