name: Deck CI

on:
  pull_request:
    paths:
      - 'packages/amazon/package.json'
      - 'packages/appengine/package.json'
      - 'packages/azure/package.json'
      - 'packages/cloudfoundry/package.json'
      - 'packages/core/package.json'
      - 'packages/docker/package.json'
      - 'packages/ecs/package.json'
      - 'packages/google/package.json'
      - 'packages/huaweicloud/package.json'
      - 'packages/kubernetes/package.json'
      - 'packages/oracle/package.json'
      - 'packages/titus/package.json'

env:
  NODE_VERSION: 10.15.1

jobs:
  test:
    name: Approve package bumps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure package bumps are pure
        id: purebump
        run: scripts/assert_package_bumps_standalone.sh

      - name: Approve package bump
        if: steps.purebump.outputs.ispurebump == 'true'
        # pin to v2.0.0 tag by commit hash
        uses: hmarr/auto-approve-action@7782c7e2bdf62b4d79bdcded8332808fd2f179cd
        with:
          github-token: '${{ secrets.SPINNAKERBOT_TOKEN }}'

      - name: Add ready to merge label
        if: steps.purebump.outputs.ispurebump == 'true'
        # pin to v3.0.0 tag by commit hash
        uses: actions/github-script@626af12fe9a53dc2972b48385e7fe7dec79145c9
        with:
          github-token: ${{ secrets.SPINNAKERBOT_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ready to rebase']
            })
