name: Deck CI

on:
  pull_request:

env:
  NODE_VERSION: 10.15.1

jobs:
  test:
    name: Approve package bumps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ready to merge label
        uses: actions/github@v1.0.0
        with:
          args: label "ready to merge"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
