name: Deck CI

on:
  pull_request:
  push:
    branches:
    - master
    - release-*

env:
  NODE_VERSION: 10.15.1

jobs:
  purebump:
    name: Ensure package bumps are pure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Ensure package bumps are pure
        run: app/scripts/modules/assert_package_bumps_standalone.sh

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: /home/runner/.cache/yarn
          key: yarn
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION  }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Unit Tests
        run: yarn test

  build:
    name: Production Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: /home/runner/.cache/yarn
          key: yarn
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION  }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Unit Tests
        run: yarn build

  packages:
    name: Build Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages:
          ['core amazon docker titus', 'appengine azure cloudfoundry', 'ecs oracle', 'google huaweicloud kubernetes']

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION  }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Build NPM Packages
        run: app/scripts/modules/build_modules.sh ${{ matrix.packages }}
