name: Create package bump PR

concurrency:
  group: create-package-bump-pr
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - 'lerna'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          git config user.name spinnakerbot
          git config user.email spinnakerbot@spinanker.io

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION  }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Bump packages
        run: npx lerna version --conventional-commits --yes

      - name: Get bumped packages
        id: bumps
        run: git log -1 --pretty=%B |

      - name: Create Pull Request
        id: createpullrequest
        if: ${{ steps.bumps.outputs.bumps != '' }}
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'chore(package): Publish ${{ steps.bumps.outputs.bumps }}'
          title: 'chore(package): Publish ${{ steps.bumps.outputs.bumps }}'
          body: |
            chore(package): Publish ${{ steps.bumps.outputs.bumps }}

            ```
            ${{ steps.bumps.outputs.changelog }}
            ```

            Auto-generated by `.github/workflows/lerna-release-pr.yml`

      - name: Apply Merge Label
        if: ${{ steps.createpullrequest.outputs.pr_number != '' }}
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.createpullrequest.outputs.pr_number }},
              labels: ['ready to merge']
            });
