name: Create package bump PR

concurrency:
  group: create-package-bump-pr
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: git - configure commit user
        run: |
          git config user.name spinnakerbot
          git config user.email spinnakerbot@spinanker.io

      - uses: actions/setup-node@v1
        name: node - setup
        with:
          node-version: ${{ env.NODE_VERSION  }}

      - name: yarn - get cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn - Install Dependencies
        run: yarn --frozen-lockfile

      - name: lerna - Bump packages
        run: |
          npx lerna version --yes --no-push --conventional-commits

      - name: gha - get bumped packages
        id: bumps
        run: |
          .github/gha_output_bumped_packages.sh
          .github/gha_output_changelog.sh

      - name: git - use conventional commit
        run: |
          git commit --amend -m "$(git log -1 --pretty=%B | sed -e 's/^Publish/chore(publish): publish packages/')"

      - name: Create Pull Request
        id: createpullrequest
        if: ${{ steps.bumps.outputs.bumps != '' }}
        uses: peter-evans/create-pull-request@v3
        with:
          # TODO: use a spinnakerbot Personal Access Token
          github-token: '${{ secrets.SPINNAKERBOT_TOKEN }}'
          commit-message: 'chore(package): Publish ${{ steps.bumps.outputs.bumps }}'
          title: 'chore(package): Publish ${{ steps.bumps.outputs.bumps }}'
          body: |
            chore(package): Publish ${{ steps.bumps.outputs.bumps }}

            ${{ steps.bumps.outputs.changelog }}

            Auto-generated by `.github/workflows/lerna-release-pr.yml`

      - name: Approve package bump
        if: ${{ steps.bumps.outputs.bumps != '' }}
        # pin to v2.0.0 tag by commit hash
        uses: hmarr/auto-approve-action@7782c7e2bdf62b4d79bdcded8332808fd2f179cd
        with:
          github-token: '${{ secrets.SPINNAKERBOT_TOKEN }}'
