name: Publish core

on:
  push:
    branches:
      - 'master'
    paths:
      - 'app/scripts/modules/core/package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 10.15.1
      - name: publish core
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          app/scripts/modules/github_actions_publish.sh core
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
