on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please-app:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
          command: manifest
          config-file: '.github/release-please-config.json'
          manifest-file: '.github/release-please-manifest.json'
          pull-request-title-pattern: 'chore${scope}: release${component} packages ${version}.'
