name: Sync Secrets

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry Run'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Sync Secrets
        uses: jpoehnelt/secrets-sync-action@v1.10.0
        with:
          SECRETS: |
            ^NPM_AUTH_TOKEN$
          REPOSITORIES: |
            ^spinnaker/spinnaker$
          DRY_RUN: ${{ github.event.inputs.dry_run }}
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

