name: Sync Secrets

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry Run'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Sync Secrets
        uses: jpoehnelt/secrets-sync-action@v1.9.0
        with:
          SECRETS: |
            ^SECRET_TO_SYNC$
          REPOSITORIES: |
            ^link108/sync-secrets-to$
          DRY_RUN: ${{ github.event.inputs.dry_run }}
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
        env:
          SECRET_TO_SYNC: ${{ secrets.NPM_AUTH_TOKEN }}

